### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by TrollWarlord** [couchbaselabs/go-couchbase#35]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with go-couchbase. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable go-couchbase on @Sourcegraph by going to https://sourcegraph.com/github.com/couchbaselabs/go-couchbase and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by maniktaneja** [comment]
Done
